version: 2.1 
orbs:
   node: circleci/node@5.0.0
   heroku: circleci/heroku@1.0.1
jobs: 
  build-and-test: 
    docker: 
      - image: circleci/ruby:2.7.4 
        environment: 
          BUNDLE_JOBS: 3
          BUNDLE_RETRY: 3
          BUNDLE_PATH: vendor/bundle
          PGHOST: 127.0.0.1
          PGUSER: postgres
          RAILS_ENV: test
      - image: circleci/postgres:11
        environment: 
          POSTGRES_USER: postgres
          POSTGRES_DB: boardTogether_test
          POSTGRES_HOST_AUTH_METHOD: trust
    steps: 
      - checkout 
      - node/install:
          install-yarn: true
          node-version: '16.13'
      - run:
          name: Force Bundler Version
          command: |
            echo 'export BUNDLER_VERSION=$(cat Gemfile.lock | tail -1 | tr -d " ")' >> $BASH_ENV
            source $BASH_ENV
            gem install bundler
      - restore_cache: # new
          keys:
            - v1-dependencies-{{ checksum "Gemfile.lock" }}
            - v1-dependencies-
      - run:
          name: Bundle Install
          command: bundle install
      - save_cache: # new
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}
      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run:
          name: Database setup
          command: bin/rails db:{create,migrate} --trace
      - run:
          name: Run rspec in parallel
          command: bundle exec rspec
      - store_test_results: 
          path: test_results
workflows:
  build-test-deploy:
    jobs:
      - build-and-test
